"""Offline scaffolding — generate skeleton blueprints from conventions.

These helpers turn a name (and optionally some line items / dimensions) into a
ready-to-fill blueprint that already follows the kit's DISCO + naming rules, so
a modeler starts from a correct shape instead of a blank page. Pure local
string generation — no tenant.
"""

from __future__ import annotations

from .blueprint import render_module
from .model import Disco, LineItem, Module

# The kit's canonical shared dimensions (see templates/naming-conventions.md and
# blueprints/_common). Used to seed scaffolds with sensible Applies To.
ORG_DIMENSION = "L3 Cost Centre"
TIME_DIMENSION = "Time"
VERSIONS_DIMENSION = "Versions"
CANONICAL_DIMENSIONS = [ORG_DIMENSION, TIME_DIMENSION, VERSIONS_DIMENSION]


def scaffold_module(
    name: str,
    disco: Disco,
    dimensions: list[str],
    line_items: list[LineItem] | None = None,
) -> str:
    """Return a Markdown blueprint for a skeleton module.

    If ``line_items`` is None, a couple of placeholder line items are inserted
    so the resulting table is illustrative (and lints cleanly).
    """
    dims = list(dimensions)
    if line_items is not None:
        # Apply the module's dimensions to any provided line item that didn't
        # bring its own Applies To, so the scaffold's grain is consistent.
        for li in line_items:
            if not li.applies_to:
                li.applies_to = list(dims)
    if line_items is None:
        line_items = [
            LineItem(
                name="Placeholder Input",
                format="Number",
                summary="Sum",
                applies_to=dims,
                formula=None,
            ),
            LineItem(
                name="Placeholder Result",
                format="Number",
                summary="Sum",
                applies_to=dims,
                formula="-- replace with your formula",
            ),
        ]
    module = Module(name=name, disco=disco, line_items=line_items)
    return render_module(module)


def scaffold_feature(feature_name: str) -> dict[str, str]:
    """Return a canonical DISCO skeleton for a new feature.

    Produces one module of each DISCO type (DAT/INP/SYS/CAL/OUT) using correct
    prefixes and the canonical Time/Org dimensions, plus a short README string.
    The keys are suggested filenames; values are Markdown blueprints.
    """
    name = (feature_name or "Feature").strip()

    org_time_ver = list(CANONICAL_DIMENSIONS)

    dat = Module(
        name="DAT01 Source Data",
        disco=Disco.DATA,
        line_items=[
            LineItem(
                "Amount (raw)",
                "Number",
                "Sum",
                org_time_ver,
                "import — landing zone, do not calculate here",
            ),
        ],
    )
    inp = Module(
        name="INP01 Assumptions",
        disco=Disco.INPUTS,
        line_items=[
            LineItem("Driver", "Number", "Sum", org_time_ver, "input — the number a planner types"),
        ],
    )
    sys = Module(
        name="SYS01 Time Settings",
        disco=Disco.SYSTEM,
        line_items=[
            LineItem(
                "Is Actual?",
                "Boolean",
                None,
                [TIME_DIMENSION],
                "flag — TRUE for closed/actual periods",
            ),
        ],
    )
    cal = Module(
        name="CAL01 Calculation",
        disco=Disco.CALC,
        line_items=[
            LineItem(
                "Result",
                "Number",
                "Sum",
                org_time_ver,
                "INP01 Assumptions.Driver * DAT01 Source Data.Amount (raw)",
            ),
        ],
    )
    out = Module(
        name="OUT01 Report",
        disco=Disco.OUTPUTS,
        line_items=[
            LineItem(
                "Reported Value",
                "Number",
                "Sum",
                [ORG_DIMENSION, TIME_DIMENSION],
                "CAL01 Calculation.Result",
            ),
        ],
    )

    readme = (
        f"# {name} — modeling skeleton\n\n"
        "A canonical DISCO scaffold generated by `anaplan-model scaffold feature`.\n"
        "Build and fill in this order (data flows the same way):\n\n"
        "1. `DAT01 Source Data` — Data: imported source rows, as-is.\n"
        "2. `INP01 Assumptions` — Inputs: numbers planners type.\n"
        "3. `SYS01 Time Settings` — System: time flags & mappings (built once).\n"
        "4. `CAL01 Calculation` — Calculations: the engine room (one step per line item).\n"
        "5. `OUT01 Report` — Outputs: reporting view, no new logic.\n\n"
        "Lint a filled-in blueprint with `anaplan-model lint <file>.md`.\n"
    )

    return {
        "README.md": readme,
        "DAT01-source-data.md": render_module(dat),
        "INP01-assumptions.md": render_module(inp),
        "SYS01-time-settings.md": render_module(sys),
        "CAL01-calculation.md": render_module(cal),
        "OUT01-report.md": render_module(out),
    }
